#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

#
# Event nethserver-owncloud-update 
#
event_actions("nethserver-owncloud-update", qw(
  initialize-default-databases 00
  nethserver-owncloud-conf 20
  nethserver-owncloud-conf-ldap 95
));

event_templates("nethserver-owncloud-update", qw(
  /etc/httpd/conf.d/default-virtualhost.inc
  /etc/httpd/conf.d/owncloud.conf
  /etc/yum.conf
  /var/www/html/owncloud/apps/user_ldap/appinfo/register_command.php
));

event_services("nethserver-owncloud-update", qw(
  httpd restart
));


