#!/usr/bin/perl
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
package esmith;

use Errno;
use esmith::util;
use NethServer::Directory;

my $exitCode = 0; 

# sql symlink
symlink "/var/www/html/owncloud/sql/owncloud.sql",
    "/etc/e-smith/sql/init/10owncloud.sql";

system ("/sbin/service mysql.init start"); 

my $ldap = NethServer::Directory->new();

# Register owncloud service account in LDAP:
$ldap->configServiceAccount('owncloud', NethServer::Directory::FIELDS_READ) || $exitCode++;

exit ($exitCode>0?1:0); 
