#!/usr/bin/perl
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
package esmith;

use Errno;
use esmith::util;
use esmith::ConfigDB;
use esmith::NetworksDB;
use NethServer::Password;

my $db = esmith::ConfigDB->open_ro();
my $domain = $db->get('DomainName')->value;
my $system = $db->get('SystemName')->value;
my $url = $system.'.'.$domain;
my $ip = esmith::NetworksDB->open_ro()->green->prop("ipaddr");
my $password = NethServer::Password::store('ownuser');

# check if owncloud db tables exists
my $res = `/usr/bin/mysql --defaults-file=/root/.my.cnf -e "select count(*) from information_schema.tables where table_type = 'BASE TABLE' and table_schema = 'owncloud'" | tail -n1`;

if ($res == 0) {
    # clear installation
    my $autoconf = '
    <?php
    $AUTOCONFIG = array(
      "trusted_domains" => array("'.$ip.'", "'.$url.'"),
      "dbtype"        => "mysql",
      "dbname"        => "owncloud",
      "dbuser"        => "ownuser",
      "dbpass"        => "'.$password.'",
      "dbhost"        => "localhost",
      "dbtableprefix" => "",
      "adminlogin"    => "admin",
      "adminpass"     => "Nethesis,1234",
      "directory"     => "/var/www/html/owncloud/data",
    );';

    open (FILE, '>/var/www/html/owncloud/config/autoconfig.php');
    print FILE $autoconf;
    close FILE;

} else {
    # upgrade
    my $trustedDomains = $ip.','.$url;
    my $dbTrustedDomains = $db->get_prop('owncloud', 'TrustedDomains') || "";

    if ($dbTrustedDomains ne "") {
        $trustedDomains = $trustedDomains.','.$dbTrustedDomains;
    }

    my $filename = '/var/www/html/owncloud/config/config.php';
    system("/usr/bin/php /var/www/html/owncloud/config/fix_oc_config.php $filename $password $trustedDomains");
}


# initialize grants mysql owncloud database
system('/usr/bin/mysql --defaults-file=/root/.my.cnf -e "CREATE DATABASE IF NOT EXISTS owncloud;"');
system('/usr/bin/mysql --defaults-file=/root/.my.cnf -e "grant all on owncloud.* to \'ownuser\'@\'localhost\' identified by \''.$password.'\'"');
system('/usr/bin/mysql --defaults-file=/root/.my.cnf -e "FLUSH PRIVILEGES"');
