#!/bin/bash

CONFIG_FILE="/var/www/html/owncloud/config/config.php"

function OCC
{
    params=$@;
    cd /var/www/html/owncloud/
    runuser -s /bin/bash apache -c "./occ $params"
}

password=`perl -e "use NethServer::Password; print NethServer::Password::store('ownuser');"`

# initialize grants mysql owncloud database
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "CREATE DATABASE IF NOT EXISTS owncloud;"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "grant all on owncloud.* to 'ownuser'@'localhost' identified by '$password';"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "FLUSH PRIVILEGES"


res=`/usr/bin/mysql --defaults-file=/root/.my.cnf -e "select count(*) from information_schema.tables where table_type = 'BASE TABLE' and table_schema = 'owncloud'" | tail -n1`;

if [[ $res == '0' ]]; then
    OCC "maintenance:install  --database mysql --database-name owncloud --database-pass $password --database-user ownuser --admin-user admin  --admin-pass Nethesis,1234 --data-dir /var/lib/nethserver/owncloud/"

    curl -s -k https://$url/owncloud/index.php > /dev/null
    sed -i "$ d" $CONFIG_FILE
    sed -i "/forcessl/d" $CONFIG_FILE
    sed -i "/check_for_working_webdav/d" $CONFIG_FILE
    sed -i "/updatechecker/d" $CONFIG_FILE
    echo "  'forcessl' => true," >> $CONFIG_FILE
    echo "  'check_for_working_webdav' => false," >> $CONFIG_FILE
    echo "  'updatechecker' => false," >> $CONFIG_FILE
    echo ");" >> $CONFIG_FILE

    ip=`perl -e 'use esmith::NetworksDB; print esmith::NetworksDB->open_ro()->green->prop("ipaddr");'`
    fqdn=`/sbin/e-smith/config get SystemName`.`/sbin/e-smith/config get DomainName`
    php /usr/share/owncloud/nethserver/fix_oc_config.php $CONFIG_FILE $ip,$fqdn
fi

